[build]
  command = "yarn build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/astro_ssr"
  status = 200
  force = true

[dev]
  framework = "astro"
  targetPort = 3000

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"